# Shared DO settings for onboarding (Solution 02)

do_hostname: "bigip01.example.com"
do_dns_servers:
  - "8.8.8.8"
  - "8.8.4.4"
do_dns_search:
  - "example.com"

do_ntp_servers:
  - "0.pool.ntp.org"
  - "1.pool.ntp.org"
do_timezone: "America/Chicago"

do_internal_vlan_tag: 100
do_internal_interface: "1.1"
do_internal_self: "10.1.10.10/24"
do_internal_floating_self: "10.1.10.20/24"
do_default_gw: "10.1.10.1"
